//
// Created by YWvin on 2026/3/24.
//

#ifndef MINIPARTICLESIMULATOR_HARDWARERENDERER_HPP
#define MINIPARTICLESIMULATOR_HARDWARERENDERER_HPP


class HardwareRenderer {
};


#endif //MINIPARTICLESIMULATOR_HARDWARERENDERER_HPP